---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-pv-8gi
  labels:
    app: awx
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/awx-projects-8gi
    type: DirectoryOrCreate
